version: '3.7'
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: .env
  db:
    image: postgres:14
    volumes:
      - ./data:/var/lib/postgresql/data
    environment: .env